version: '3.1'

services:
  # Mongo Service
  mongo:
    image: mongo:latest
    container_name: "mongo-3b"
    environment:
      - MONGO_INITDB_DATABASE=init_db
    volumes:
      - ./mongo_data:/data/db
      - ./mongo_config:/data/configdb
    ports:
      - "27017-27019:27017-27019"
  #challenge_3b_stores
  app: &challenge_3b_stores
    build:
      context: ../../
      dockerfile: Dockerfile
    volumes:
      - ../../:/app
    depends_on:
      - mongo
    env_file:
      - ../../.env
    ports:
      - "8003:8003"
    command: uvicorn config:app --host=0.0.0.0 --port=8003 --reload --log-level=info
